{% set name = "beakerx_all" %}
  {% set version = "2.1.0" %}
  {% set kversion = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/twosigma/beakerx.git
  git_tag: master

source:
  #url: https://files.pythonhosted.org/packages/source/b/beakerx/{{ name }}-{{ version }}.tar.gz
  url: file:///Users/ildipo/src/beakerx/beakerx-dist/dist/{{ name }}-{{ version }}.tar.gz

requirements:
  build:
    - python
    - pip
  run:
    - beakerx_base>={{ version }}
    - beakerx_kernel_groovy>={{ kversion }}
    - beakerx_kernel_java>={{ kversion }}
    - beakerx_kernel_scala>={{ kversion }}
    - beakerx_kernel_sql>={{ kversion }}
    - beakerx_kernel_clojure>={{ kversion }}
    - beakerx_kernel_kotlin>={{ kversion }}
    - beakerx_kernel_autotranslation>={{ kversion }}
    - beakerx_tabledisplay>={{ version }}
    - beakerx_widgets>={{ version }}
    - python >=3
    - notebook >=5.7.4
